# Generated by Django 4.2.16 on 2024-10-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_on', 'author']},
        ),
    ]
