# Generated by Django 4.2.16 on 2024-10-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='profile_image',
        ),
    ]
